[package]
name = "semantic-test-project"
version = "1.8.0"
license = "MIT"
authors = ["Jan Schulte"]
description = "test project"
repository = "https://github.com/schultyy/semantic-test-project"

[dependencies]
