[package]
name = "semantic-test-project"
version = "1.0.0"
authors = ["Jan Schulte <hello@unexpected-co.de>"]
license="MIT"
description="Test project for semantic-rs"
homepage="https://github.com/schultyy/semantic-test-project"

[dependencies]
